openapi: 3.0.3

info:
  title: Software Engineer Test App
  description: Server with api to return people listed as living in London or currently within 50 miles based on geographical coordinates
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /search:
    get:
      description: Returns from bpdts-test-app all matching people listed as living in London or currently within 50 miles of London
      operationId: searchForPeople
      responses:
        200:
          description: A list of matching records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/person'

components:
  schemas:
    person:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        ip_address:
          type: string
        latitude:
          type: number
        longitude:
          type: number
